### ISSUE TITLE
3133

### ISSUE THREAD

**Issue by BratishkaErik** [DorianXGH/Lukarnel#2]
> [PAUSED] Developpement of a zig kernel is paused while the language is unstable. It will resume once the language is more mature and issue 3133 is solved.

I want to say that it was recently „rejected in favor of ziglang/zig#5049 and ziglang/zig#10113.”

https://github.com/ziglang/zig/issues/3133#issuecomment-1012748799

**Comment by DorianBourgeoisat** [comment]
Thanks for the heads up, I look forward to the infamous packed struct problem being solved at last xD I think I'll continue development of the kernel in C for now at least, but nice to know that #3133 is no longer being postponed release after release x)

**Comment by BratishkaErik** [comment]
Also see https://github.com/ziglang/zig/commit/6249a24e81b9b3df3d5ca99b57f22470b9ac486c

```
This implements https://github.com/ziglang/zig/issues/10113 for the self-hosted compiler only. It removes the
ability to override alignment of packed struct fields, and removes the
ability to put pointers and arrays inside packed structs.

After this commit, nearly all the behavior tests pass for the stage2 llvm
backend that involve packed structs.

I didn't implement the compile errors or compile error tests yet. I'm
waiting until we have stage2 building itself and then I want to rework
the compile error test harness with inspiration from Vexu's arocc test
harness. At that point it should be a much nicer dev experience to work
on compile errors.
```

**Comment by BratishkaErik** [comment]
Also see https://github.com/ziglang/zig/pull/12379
```
Now the backing integer of a packed struct type may be explicitly
specified with e.g. packed struct(u32) { ... }.

I haven't touched Sema.zig this extensively before, so any code/style pointers there are certainly appreciated.

Related: https://github.com/ziglang/zig/issues/10113, https://github.com/ziglang/zig/issues/5049
```
